apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: deploy
  name: web-app
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["*"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
